targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          explicit_to_json: true
      freezed:
        options:
          copy_with: false
          equal: false