name: carewool_profitability_calculator
description: Course and diploma project
publish_to: 'none'

version: 0.2.1+3

environment:
  sdk: '>=3.0.0-286.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  event: ^2.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  provider: ^6.0.5
  rxdart: ^0.27.7
  dfunc: ^0.8.1
  get_it: ^7.2.0
  sembast: ^3.4.3+1
  path_provider: ^2.0.14
  path: ^1.8.3
  intl: ^0.18.0
  auto_route: ^6.3.0
  flutter_native_splash: ^2.2.19
  logger: ^1.3.0
  excel: ^2.1.0
  file_picker: ^5.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.1
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  auto_route_generator: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
