name: carewool_profitability_calculator
description: Course and diploma project
publish_to: 'none'

version: 0.3.2+6

environment:
  sdk: '>=3.0.0-286.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  rxdart: ^0.27.7
  dfunc: ^0.8.1
  get_it: ^7.2.0
  path_provider: ^2.0.14
  path: ^1.8.3
  intl: ^0.18.0
  auto_route: ^7.2.0
  flutter_native_splash: ^2.2.19
  logger: ^1.3.0
  excel: ^2.1.0
  file_picker: ^5.2.11
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_typeahead: ^4.3.8
  url_launcher: ^6.1.11
  pdf: ^3.10.3
  printing: ^5.10.4
  permission_handler: ^10.2.0
  external_path: ^1.0.3
  flutter_file_dialog: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.6.1
  freezed: ^2.3.2
  build_runner: ^2.4.1
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  auto_route_generator: ^7.1.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
