name: carewool_profitability_calculator
description: Course and diploma project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-286.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  event: ^2.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  build_runner: ^2.4.1
  freezed: ^2.3.2
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  provider: ^6.0.5
  rxdart: ^0.27.7
  dfunc: ^0.8.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
